version: '3'

networks:
  graylog_net:
    driver: bridge

volumes:
  web_db_data: {}
  web_db_data_backups: {}
  graylog_mongo_data: {}
  graylog_elastic_data: {}
  graylog_config: {}
  graylog_journal: {}

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo: # Database for graylog
    image: mongo:4.2
    volumes:
      - graylog_mongo_data:/data/db
    networks:
      - graylog_net
    logging: # Logging configuration to send docker logs to graylog
      driver: "gelf"
      options:
        gelf-address: "udp://${graylog}:12201"
        tag: "mongo-logs"
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch: # Database for graylog
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - graylog_elastic_data:/usr/share/elasticsearch/data
    networks:
      - graylog_net
    logging: # Logging configuration to send docker logs to graylog
      driver: "gelf"
      options:
        gelf-address: "udp://${graylog}:12201"
        tag: "elastic-logs"
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog: # Graylog instance
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog_net
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - graylog_config:/usr/share/graylog/data/config
  web_db: # Database for django project
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - web_db_data:/var/lib/postgresql/data:Z
      - web_db_data_backups:/backups:z
    logging: # Logging configuration to send docker logs to graylog
      driver: "gelf"
      options:
        gelf-address: "udp://${graylog}:12201"
        tag: "postgres-logs"
  web: # Simple django project
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - web_db
      - graylog
    networks:
      - graylog_net